name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: yandex/clickhouse-server:latest
        ports:
          - 9000:9000
          - 8123:8123
        options: >
          --health-cmd="curl -f http://localhost:8123 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --with dev

    - name: Docker ps for debugging
      run: docker ps -a

    - name: Wait for ClickHouse service to be healthy
      run: |
        until curl -sSf http://localhost:8123; do
          echo "Waiting for ClickHouse to be up..."
          sleep 5
        done

    - name: Run ruff
      run: poetry run ruff .

    - name: Run tests
      run: poetry run pytest