name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    environment: pypi-publish

    services:
      clickhouse:
        image: yandex/clickhouse-server:latest
        ports:
          - 9000:9000
          - 8123:8123
        options: --health-cmd='curl -f http://localhost:8123 || exit 1' --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --with dev

    - name: Wait for ClickHouse service to be healthy
      run: |
        while ! curl -sSf http://localhost:8123 > /dev/null; do
          echo "Waiting for ClickHouse to be up..."
          sleep 5
        done

    - name: Run ruff
      run: poetry run ruff .

    - name: Run tests
      run: poetry run pytest

    - name: Build package
      run: poetry build

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish --username $TWINE_USERNAME --password $TWINE_PASSWORD
